qlib_init:
  # Using the absolute path you confirmed
  provider_uri: /home/yuyangwu/.qlib/qlib_data/crypto_data
  region: us

task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      loss: mse
      colsample_bytree: 0.8879
      learning_rate: 0.0421
      subsample: 0.8789
      lambda_l1: 205.6999
      lambda_l2: 580.9768
      max_depth: 8
      num_leaves: 210
      num_threads: 20
      verbosity: -1

  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        
        # This is the corrected structure with no extra 'kwargs:'
        instruments: crypto_list
        start_time: 2020-01-01
        end_time: 2025-07-01
        fit_start_time: 2020-01-01
        fit_end_time: 2023-12-31
        data_loader:
          class: QlibDataLoader
          module_path: qlib.data.dataset.loader
          kwargs:
            config:
              feature:
                - "(Ref($close, 1) / $close) - 1"
                - "($high - $low) / $close"
                - "($close / Mean($close, 5)) - 1"
                - "($volume / Mean($volume, 20)) - 1"
              label: ["Ref($close, -2)/Ref($close, -1) - 1"]
      
      segments:
        # A 1-month warm-up is enough for our simple features
        train: [2020-02-01, 2023-12-31]
        valid: [2024-01-01, 2024-12-31]
        test: [2025-01-01, 2025-07-01]

  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp